import type { Metadata } from "next";
import AutoLogin from "./components/AutoLogin";
import LoadingModal from "./components/LoadingModal";
import Snackbar from "./components/Snackbar";
import "./globals.css";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={` antialiased`}>
                <AutoLogin />
                {children}
                <LoadingModal />
                <Snackbar />
            </body>
        </html>
    );
}
