import { COLOR } from "@/app/types";

export const colors: Array<COLOR> = [
    COLOR.RED,
    COLOR.ORANGE,
    COLOR.CORAL,
    COLOR.GOLD,
    COLOR.YELLOW,
    COLOR.AMBER,
    COLOR.LIME,
    COLOR.GREEN,
    COLOR.EMERALD,
    COLOR.OLIVE,
    COLOR.TEAL,
    COLOR.CYAN,
    COLOR.SKY,
    COLOR.BLUE,
    COLOR.INDIGO,
    COLOR.NAVY,
    COLOR.PURPLE,
    COLOR.VIOLET,
    COLOR.MAGENTA,
    COLOR.PINK,
    COLOR.CRIMSON,
    COLOR.MAROON,
    COLOR.BROWN,
    COLOR.SILVER,
];

export const colorMap = {
    [COLOR.RED]: "#ef4444",
    [COLOR.ORANGE]: "#f97316",
    [COLOR.CORAL]: "#fb7185",
    [COLOR.GOLD]: "#facc15",
    [COLOR.YELLOW]: "#eab308",
    [COLOR.AMBER]: "#f59e0b",
    [COLOR.LIME]: "#84cc16",
    [COLOR.GREEN]: "#10b981",
    [COLOR.EMERALD]: "#059669",
    [COLOR.OLIVE]: "#808000",
    [COLOR.TEAL]: "#14b8a6",
    [COLOR.CYAN]: "#06b6d4",
    [COLOR.SKY]: "#0ea5e9",
    [COLOR.BLUE]: "#3b82f6",
    [COLOR.INDIGO]: "#6366f1",
    [COLOR.NAVY]: "#000080",
    [COLOR.PURPLE]: "#a855f7",
    [COLOR.VIOLET]: "#8b5cf6",
    [COLOR.MAGENTA]: "#d946ef",
    [COLOR.PINK]: "#ec4899",
    [COLOR.CRIMSON]: "#dc143c",
    [COLOR.MAROON]: "#800000",
    [COLOR.BROWN]: "#a78b59",
    [COLOR.SILVER]: "#c0c0c0",
} as const;
